import { Color3 } from './Color3.js';
import { Vec3 } from './Vec3.js';
export declare function color3Equals(a: Color3, b: Color3, tolerance?: number): boolean;
export declare function color3Add(a: Color3, b: Color3, result?: Color3): Color3;
export declare function color3Subtract(a: Color3, b: Color3, result?: Color3): Color3;
export declare function color3MultiplyByScalar(a: Color3, b: number, result?: Color3): Color3;
export declare function color3Negate(a: Color3, result?: Color3): Color3;
export declare function color3Length(a: Color3): number;
export declare function color3Normalize(a: Color3, result?: Color3): Color3;
export declare function color3Dot(a: Color3, b: Color3): number;
export declare function color3Lerp(a: Color3, b: Color3, t: number, result?: Color3): Color3;
export declare function color3FromArray(array: Float32Array | number[], offset?: number, result?: Color3): Color3;
export declare function color3ToArray(a: Color3, array: Float32Array | number[], offset?: number): void;
export declare function color3ToString(a: Color3): string;
export declare function color3Parse(text: string, result?: Color3): Color3;
export declare function hslToColor3(hsl: Vec3, result?: Color3): Color3;
export declare function color3ToHSL(rgb: Color3, result?: Vec3): Vec3;
export declare function hexToColor3(hex: number, result?: Color3): Color3;
export declare function color3ToHex(rgb: Color3): number;
export declare function color3ToHexString(rgb: Color3): string;
export declare function hexStringToColor3(hex: string, result?: Color3): Color3;
//# sourceMappingURL=Color3.Functions.d.ts.map