export enum PhysicalMaterialOutputs {
  Beauty = 0,
  AlphaMode,
  Alpha,
  Albedo,
  SpecularRoughness,
  Metallic,
  Emissive,
  Normal,
  SpecularColor,
  SpecularFactor,
  IOR,
  ClearcoatFactor,
  ClearcoatRoughness,
  ClearcoatTint,
  ClearcoatNormal,
  SheenColor,
  SheenRoughness,
  Anisotropic,
  AnisotropicDirection,
  Transmission,
  Thickness,
  AttenuationDistance,
  AttenuationColor,
  Iridescence,
  IridescenceIOR,
  IridescenceThickness
}
